FROM node:18-alpine as build

WORKDIR /frontend

COPY package*.json .

RUN npm ci --force

COPY . .

RUN npm run build



FROM nginx:latest

COPY --from=build /frontend/dist/frontend /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]









